steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/lina/lina-app:latest', '-f', 'Dockerfile.app', '.']
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/lina/lina-app:latest'
