steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/lina/lina-worker:latest', '-f', 'Dockerfile.worker', '.']
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/lina/lina-worker:latest'
