const assert = require('node:assert/strict');
const test = require('node:test');
const {validateProcess, nextViewState, initialProcessState} = require(process.env.PROCESS_CHECKPOINT_COMPILED + '/process-model.js');
const scene={topology:'sequence',stages:[{id:'a',label:'First',detail:'One',art:'drop'},{id:'b',label:'Second',detail:'Two',art:'drop'}],relations:[{id:'a-b',from:'a',to:'b',label:'Then'}]};
test('only explicit source-supported return makes a cycle',()=>{assert.equal(validateProcess(scene),true);assert.equal(validateProcess({...scene,topology:'cycle'}),false);assert.equal(validateProcess({...scene,topology:'cycle',relations:[...scene.relations,{id:'b-a',from:'b',to:'a',label:'Next generation'}]}),true)});
test('reject duplicate IDs, dangling edges and unsupported topology',()=>{assert.equal(validateProcess({...scene,stages:[scene.stages[0],scene.stages[0]]}),false);assert.equal(validateProcess({...scene,topology:'branched'}),false);assert.equal(validateProcess({...scene,relations:[{id:'a-x',from:'a',to:'x',label:'Then'}]}),false)});
test('selection and reveal preserve content and reject unknown targets',()=>{const s={selectedId:null,revealedIds:['a']}; const x=nextViewState(scene,s,{type:'select',id:'b'});assert.equal(x.selectedId,'b');assert.deepEqual(x.revealedIds,['a','b']);assert.deepEqual(nextViewState(scene,x,{type:'reveal',id:'b'}).revealedIds,['a','b']);assert.deepEqual(nextViewState(scene,s,{type:'select',id:'bad'}),s);assert.equal(scene.stages[1].detail,'Two')});
const {readProcessScene}=require(process.env.PROCESS_CHECKPOINT_COMPILED + '/process-model.js');
const {processReviewScenes,reviewScene}=require(process.env.PROCESS_CHECKPOINT_COMPILED + '/process-review-data.js');
const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');const {ProcessView}=require(process.env.PROCESS_CHECKPOINT_COMPILED + '/process-view.js');
test('strict data reader accepts all fixtures and rejects unknown fields, executable art and ninth stage',()=>{for(const s of processReviewScenes)assert.ok(readProcessScene(s));for(const bad of [null,{}, {...processReviewScenes[0],callback:'javascript'}, {...processReviewScenes[0],stages:[{...processReviewScenes[0].stages[0],art:'<svg/>'}]}])assert.equal(readProcessScene(bad),null);const eight={...processReviewScenes[0],stages:Array.from({length:8},(_,i)=>({id:String(i),label:'Stage',detail:'Detail',art:'idea'})),relations:Array.from({length:7},(_,i)=>({id:`edge-${i}`,from:String(i),to:String(i+1),label:'Then'}))};assert.ok(readProcessScene(eight));assert.equal(readProcessScene({...eight,stages:[...eight.stages,{id:'8',label:'Ninth',detail:'D',art:'idea'}]}),null)});
test('one renderer displays all datasets, English/Arabic and explicit cycle return',()=>{for(let i=0;i<3;i++)for(const ar of [false,true]){const scene=reviewScene(i,ar);const html=renderToStaticMarkup(React.createElement(ProcessView,{scene,state:{selectedId:scene.stages[0].id,revealedIds:[scene.stages[0].id]},onAction:()=>{},onExplain:()=>{}}));assert.ok(html.includes(scene.title));assert.ok(html.includes('aria-pressed="true"'));assert.ok(html.includes(scene.stages[0].detail));assert.ok(html.includes(`dir="${ar?'rtl':'ltr'}"`));assert.ok(html.includes('direction:ltr'));assert.ok(html.includes('prefers-reduced-motion:reduce'));if(scene.topology==='cycle')assert.ok(html.includes('pv-return'));}});
test('invalid input gives text fallback instead of partially rendered scene',()=>{const html=renderToStaticMarkup(React.createElement(ProcessView,{scene:{...processReviewScenes[0],relations:[]},state:{selectedId:null,revealedIds:[]},onAction:()=>{},onExplain:()=>{}}));assert.ok(html.includes('visual is unavailable'));assert.ok(!html.includes('pv-card'))});
test('semantic focus transitions retain IDs and target only declared outgoing relations',()=>{const scene=processReviewScenes[1];const initial={selectedId:null,revealedIds:[]};const a=nextViewState(scene,initial,{type:'focus',id:'larva'});assert.equal(a.focusedStageId,'larva');assert.equal(a.selectedId,'larva');assert.deepEqual(a.highlightedRelationIds,[scene.relations[1].id]);const b=nextViewState(scene,a,{type:'focus',id:'pupa'});assert.equal(b.focusedStageId,'pupa');assert.equal(scene.stages[1].id,'larva');assert.deepEqual(nextViewState(scene,b,{type:'focus',id:'unknown'}),b);assert.deepEqual(nextViewState(scene,b,{type:'trace',id:'unknown'}),b);const traced=nextViewState(scene,b,{type:'trace',id:scene.relations[2].id});assert.equal(traced.tracingRelationId,scene.relations[2].id);assert.equal(nextViewState(scene,traced,{type:'clear'}).selectedId,null)});
test('pointer select and semantic focus command produce identical state',()=>{const scene=processReviewScenes[1];const s={selectedId:null,revealedIds:[]};assert.deepEqual(nextViewState(scene,s,{type:'select',id:'larva'}),nextViewState(scene,s,{type:'focus',id:'larva'}))});
test('cycle has one SVG spatial scene with stable declared paths, no card primary view',()=>{const scene=processReviewScenes[1];const state=nextViewState(scene,{selectedId:null,revealedIds:[]},{type:'focus',id:'larva'});const html=renderToStaticMarkup(React.createElement(ProcessView,{scene,state,onAction:()=>{},onExplain:()=>{}}));assert.ok(html.includes('class="pv-scene"'));assert.ok(html.includes('viewBox='));for(const r of scene.relations)assert.ok(html.includes(`data-relation="${r.id}"`));assert.ok(!html.includes('class="pv-card'));assert.ok(html.includes('marker-end'));});

test('strict relation identity rejects duplicate and absent IDs',()=>{const scene=processReviewScenes[1];assert.equal(readProcessScene({...scene,relations:scene.relations.map(r=>({...r,id:'same'}))}),null);const {id,...missing}=scene.relations[0];assert.equal(readProcessScene({...scene,relations:[missing,...scene.relations.slice(1)]}),null)});
test('focus interrupts tracing and clear restores complete default context',()=>{const scene=processReviewScenes[1];const a=nextViewState(scene,{selectedId:null,revealedIds:[]},{type:'focus',id:'larva'});const b=nextViewState(scene,a,{type:'trace',id:scene.relations[1].id});const c=nextViewState(scene,b,{type:'focus',id:'pupa'});assert.equal(c.tracingRelationId,null);assert.deepEqual(c.highlightedStageIds,['pupa']);assert.equal(c.activeExplanationStageId,'pupa');const clear=nextViewState(scene,c,{type:'clear'});assert.deepEqual(clear.revealedIds,[]);assert.deepEqual(clear.highlightedRelationIds,[]);assert.equal(scene.stages.length,4)});
test('detail reveal changes only semantic detail state; reduced motion preserves meaning',()=>{const scene=processReviewScenes[1];const initial=require(process.env.PROCESS_CHECKPOINT_COMPILED+'/process-model.js').initialProcessState();const state=nextViewState(scene,initial,{type:'reveal',id:'egg'});assert.equal(state.selectedId,null);assert.equal(state.activeExplanationStageId,'egg');const render=(reducedMotion)=>renderToStaticMarkup(React.createElement(ProcessView,{scene,state,reducedMotion,onAction:()=>{},onExplain:()=>{}}));assert.equal(render(false).replace('data-reduced="false"',''),render(true).replace('data-reduced="true"',''));});

test('application-owned V2 motion classes preserve semantic controls and reduced motion',()=>{const sequence={...processReviewScenes[0],motion_intents:['REVEAL_IN_ORDER','TRACE_SEQUENCE','TRANSITION_FOCUS','EMPHASIZE_RELATION']};const cycle={...processReviewScenes[1],motion_intents:['REVEAL_IN_ORDER','TRACE_CYCLE','TRANSITION_FOCUS','EMPHASIZE_RELATION']};for(const scene of [sequence,cycle]){assert.ok(readProcessScene(scene));const normal=renderToStaticMarkup(React.createElement(ProcessView,{scene,state:initialProcessState(),onAction:()=>{},onExplain:()=>{}}));const reduced=renderToStaticMarkup(React.createElement(ProcessView,{scene,state:initialProcessState(),reducedMotion:true,onAction:()=>{},onExplain:()=>{}}));for(const intent of scene.motion_intents)assert.ok(normal.includes(`pv-motion-${intent.toLowerCase()}`));assert.ok(reduced.includes('data-reduced="true"'));}assert.equal(readProcessScene({...sequence,motion_intents:['TRACE_CYCLE']}),null);assert.equal(readProcessScene({...cycle,motion_intents:['TRACE_SEQUENCE']}),null);assert.equal(readProcessScene({...cycle,motion_intents:['TRACE_CYCLE','TRACE_SEQUENCE']}),null);});

test('V2 choreography is ordered while authoritative focus and relation stay singular',()=>{const sequence={...processReviewScenes[0],motion_intents:['REVEAL_IN_ORDER','TRACE_SEQUENCE','TRANSITION_FOCUS','EMPHASIZE_RELATION']};const focused=nextViewState(sequence,initialProcessState(),{type:'focus',id:sequence.stages[1].id});const html=renderToStaticMarkup(React.createElement(ProcessView,{scene:sequence,state:focused,onAction:()=>{},onExplain:()=>{}}));for(let i=0;i<sequence.stages.length;i++)assert.ok(html.includes(`data-motion-order="${i}"`));for(let i=0;i<sequence.relations.length;i++)assert.ok(html.includes(`data-motion-order="${i}"`));assert.equal((html.match(/<g[^>]*pv-motion-focus/g)||[]).length,1);assert.equal((html.match(/<g[^>]*pv-relation-active/g)||[]).length,1);const traced=nextViewState(sequence,focused,{type:'trace',id:sequence.relations[0].id});const tracedHtml=renderToStaticMarkup(React.createElement(ProcessView,{scene:sequence,state:traced,reducedMotion:true,onAction:()=>{},onExplain:()=>{}}));assert.equal((tracedHtml.match(/<g[^>]*pv-relation-active/g)||[]).length,1);assert.ok(tracedHtml.includes('data-reduced="true"'));});

test('relation emphasis is an opt-in hook on the one authoritative relation',()=>{const scene=processReviewScenes[0],state=nextViewState(scene,initialProcessState(),{type:'focus',id:scene.stages[0].id});const withMotion=renderToStaticMarkup(React.createElement(ProcessView,{scene:{...scene,motion_intents:['EMPHASIZE_RELATION']},state,onAction:()=>{},onExplain:()=>{}}));const withoutMotion=renderToStaticMarkup(React.createElement(ProcessView,{scene,state,onAction:()=>{},onExplain:()=>{}}));assert.equal((withMotion.match(/<g[^>]*pv-motion-emphasis/g)||[]).length,1);assert.equal((withoutMotion.match(/<g[^>]*pv-motion-emphasis/g)||[]).length,0);});

test('cycle progress uses explicit English and Arabic ordinals, never fraction notation',()=>{for(const ar of [false,true])for(const [id,n] of [['egg',1],['pupa',3]]){const scene=reviewScene(1,ar);const state=nextViewState(scene,{selectedId:null,revealedIds:[]},{type:'focus',id});const html=renderToStaticMarkup(React.createElement(ProcessView,{scene,state,onAction:()=>{},onExplain:()=>{}}));const center=html.match(/<g class="pv-center"[^>]*>(.*?)<\/g>/)[1];assert.ok(center.includes(ar?`المرحلة ${n} من 4`:`Stage ${n} of 4`));assert.ok(!/\d+\s*\/\s*\d+/.test(center));}});
