import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ProcessView} from './process-view';
import {nextViewState,ProcessViewState,readProcessScene,initialProcessState} from './process-model';
import {reviewScene} from './process-review-data';
function Review(){
 const [index,setIndex]=useState(1),[arabic,setArabic]=useState(false),[narrow,setNarrow]=useState(false),[long,setLong]=useState(false),[reduced,setReduced]=useState(false);
 const [state,setState]=useState<ProcessViewState>(initialProcessState);const [explanation,setExplanation]=useState('No preview callback yet.');
 const scene=readProcessScene(reviewScene(index,arabic,long))!;
 function reset(){setState(s=>nextViewState(scene,s,{type:'clear'}));setExplanation('No preview callback yet.')}
 return <main className={reduced?"review-reduced":""}><style>{`.review-reduced .pv-card{transition:none}.review-reduced .pv-detail p{animation:none}body{margin:0;background:#f2f3ec;font-family:Arial,sans-serif;color:#263e36}main{padding:24px}nav{max-width:1100px;margin:0 auto 20px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}nav label{display:flex;gap:7px;align-items:center;font-size:14px}nav select,nav button{font:inherit;padding:10px;border:1px solid #bccbbc;border-radius:8px;background:#fffefa;color:#263e36}nav button:focus-visible,nav select:focus-visible{outline:3px solid #9a641c}.review-note{max-width:1100px;margin:0 auto 16px;font-size:13px;line-height:1.6;color:#5a6a5e}output{display:block;max-width:1100px;margin:16px auto;font-size:14px;line-height:1.6} @media(max-width:600px){main{padding:10px}}`}</style>
 <p className="review-note">STUDIO-VISUAL-PROCESS-01 · Visual checkpoint 2 · Isolated visual review · prepared data · local callbacks only</p>
 <nav aria-label="Review controls"><label>Example<select aria-label="Example" value={index} onChange={e=>{setIndex(Number(e.target.value));reset()}}><option value="0">Science sequence</option><option value="1">Butterfly life cycle</option><option value="2">Writing process</option></select></label><label><input type="checkbox" checked={arabic} onChange={e=>setArabic(e.target.checked)}/>Arabic / mixed text</label><label><input type="checkbox" checked={narrow} onChange={e=>setNarrow(e.target.checked)}/>360 px preview</label><label><input type="checkbox" checked={long} onChange={e=>setLong(e.target.checked)}/>Long labels</label><label><input type="checkbox" checked={reduced} onChange={e=>setReduced(e.target.checked)}/>Reduced motion</label><button onClick={reset}>Reset</button></nav>
 <nav aria-label="Preview semantic controls"><strong style={{fontSize:14}}>Preview semantic controls</strong><button onClick={()=>setState(s=>nextViewState(scene,s,{type:'focus',id:scene.stages[1].id}))}>Focus {scene.stages[1].label}</button><button onClick={()=>setState(s=>nextViewState(scene,s,{type:'focus',id:scene.stages[2]?.id??scene.stages[1].id}))}>Focus {scene.stages[2]?.label??scene.stages[1].label}</button><button onClick={()=>setState(s=>nextViewState(scene,s,{type:'trace',id:(scene.relations.find(r=>r.from===s.focusedStageId)??scene.relations[0]).id}))}>Trace next relation</button><button onClick={()=>setState(s=>nextViewState(scene,s,{type:'reveal',id:s.selectedId??scene.stages[0].id}))}>Reveal detail</button><button onClick={reset}>Clear focus</button></nav>
 <div style={{maxWidth:narrow?360:1100,margin:'auto'}}><ProcessView scene={scene} state={state} onAction={a=>setState(s=>nextViewState(scene,s,a))} reducedMotion={reduced} onExplain={id=>setExplanation(`Local preview callback: ${id}. No Tutor request was sent.`)}/></div><output data-preview-state={JSON.stringify(state)} aria-live="polite">{explanation}</output>
 </main>;
}
createRoot(document.getElementById('root')!).render(<Review/>);
