import React, { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";

import { StudioRendererHost } from "../../components/daily-student/studio-renderer-host";
import type { StudioSnapshotFrame } from "../../lib/studio/contracts";

type Pattern = "NUMBER_LINE" | "PLOT" | "CYCLE" | "SHAPES" | "ARABIC" | "OLDER";

const base = { meaning: "Use the visual relationship to explain the idea.", accessibility: { text_equivalent: "A tutor-approved educational visual.", aria_label: "Educational visual" }, allowed_actions: ["FOCUS"], elements: [{ id: "focus", label: "Focus point", current_value: null }] } as const;
const math = (kind: "NUMBER_LINE" | "PLOT") => ({ ...base, block_id: `${kind.toLowerCase()}-board`, type: "MATH_BOARD" as const, title: kind === "PLOT" ? "Plot positions on a coordinate grid" : "Compare fractions on a number line", board_kind: kind, axis_min: "-4", axis_max: "4", axes: kind === "PLOT" ? [{ axis: "X" as const, minimum: "-4", maximum: "4", step: "1" }, { axis: "Y" as const, minimum: "-3", maximum: "3", step: "1" }] : [{ axis: "X" as const, minimum: "0", maximum: "1", step: "1/4" }], markers: kind === "PLOT" ? [{ id: "origin", label: "0", value: "0", marker_kind: "POINT" as const, draggable: false }, { id: "three", label: "3", value: "3", marker_kind: "POINT" as const, draggable: false }] : [{ id: "half", label: "1/2", value: "1/2", marker_kind: "POINT" as const, draggable: false }, { id: "three-quarters", label: "3/4", value: "3/4", marker_kind: "POINT" as const, draggable: false }], expressions: [] });
const definitions: Record<Pattern, { objective: string; direction: "ltr" | "rtl"; blocks: any[]; presentation: any }> = {
  NUMBER_LINE: { objective: "Place equivalent fractions precisely.", direction: "ltr", blocks: [math("NUMBER_LINE")], presentation: { layout: "FOCUS", palette: "COOL", motion: "NONE", placements: [{ block_id: "number_line-board", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: [] } },
  PLOT: { objective: "Read positions through x and y axes.", direction: "ltr", blocks: [math("PLOT")], presentation: { layout: "SPLIT", palette: "COOL", motion: "SUBTLE", placements: [{ block_id: "plot-board", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: [] } },
  CYCLE: { objective: "Trace a changing system around a cycle.", direction: "ltr", blocks: [{ ...base, block_id: "cycle", type: "DIAGRAM", title: "Water changes and returns", topology: "CYCLE", layout: "RADIAL", nodes: ["Evaporate", "Condense", "Collect", "Warm"].map((label, index) => ({ id: `cycle-${index}`, label, node_kind: "PROCESS" as const })), edges: [0, 1, 2, 3].map(index => ({ source_id: `cycle-${index}`, target_id: `cycle-${(index + 1) % 4}`, relation: index === 3 ? "RETURNS_TO" as const : "NEXT" as const, label: null })) }], presentation: { layout: "FOCUS", palette: "NATURE", motion: "REVEAL", placements: [{ block_id: "cycle", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: ["cycle"] } },
  SHAPES: { objective: "Name the shape and directional relationship.", direction: "ltr", blocks: [{ ...base, block_id: "shapes", type: "SCENE_2D", title: "Geometry field", viewport_width_units: 100, viewport_height_units: 100, objects: [{ id: "point", label: "Point", object_kind: "POINT", position: { x: "15", y: "30" }, draggable: false }, { id: "polygon", label: "Polygon", object_kind: "POLYGON", position: { x: "45", y: "55" }, draggable: false }, { id: "arrow", label: "moves", object_kind: "ARROW", position: { x: "68", y: "55" }, draggable: false }, { id: "label", label: "Target", object_kind: "LABEL", position: { x: "88", y: "55" }, draggable: false }], relations: [{ source_id: "arrow", target_id: "label", relation: "MOVES_TOWARD", label: "toward" }] }], presentation: { layout: "GRID", palette: "VIBRANT", motion: "NONE", placements: [{ block_id: "shapes", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: [] } },
  ARABIC: { objective: "رتّب المراحل ثم اشرح كيف يعود الماء إلى البداية.", direction: "rtl", blocks: [{ ...base, block_id: "arabic-cycle", type: "DIAGRAM", title: "دورة الماء", topology: "CYCLE", layout: "RADIAL", nodes: ["تبخر", "تكاثف", "هطول", "تجميع"].map((label, index) => ({ id: `ar-${index}`, label, node_kind: "PROCESS" as const })), edges: [0, 1, 2, 3].map(index => ({ source_id: `ar-${index}`, target_id: `ar-${(index + 1) % 4}`, relation: index === 3 ? "RETURNS_TO" as const : "NEXT" as const, label: null })) }], presentation: { layout: "FOCUS_SUPPORT", palette: "NATURE", motion: "REVEAL", placements: [{ block_id: "arabic-cycle", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: ["arabic-cycle"] } },
  OLDER: { objective: "Compare the same fractions with denser supporting evidence.", direction: "ltr", blocks: [math("NUMBER_LINE"), { ...base, block_id: "support", type: "TEXT_INTERACTION", title: "Compare", interaction_family: "RELATION", prompt: "Connect each claim to the number line.", groups: [{ id: "evidence", label: "Evidence" }], items: [{ id: "claim", text: "3/4 lies to the right of 1/2.", group_id: "evidence" }], relations: [] }], presentation: { layout: "GRID", palette: "NEUTRAL", motion: "NONE", placements: [{ block_id: "number_line-board", role: "PRIMARY", order: 0, span: "WIDE" }, { block_id: "support", role: "SUPPORT", order: 1, span: "NORMAL" }], reveal_order: [] } },
};

function snapshot(pattern: Pattern): StudioSnapshotFrame {
  const value = definitions[pattern]; const scene = { version: "agentic-canvas-scene-v2", objective: value.objective, subject_key: "MATH", presentation: value.presentation, blocks: value.blocks };
  return { protocol_version: "studio-protocol-v1", type: "STUDIO_SNAPSHOT", latest_event_sequence: 0, snapshot_schema_version: "studio-snapshot-v1", current_scene_id: `visual-${pattern.toLowerCase()}`, current_scene_version: 1, active_subject_key: "CANVAS", active_activity_key: "agentic_canvas", active_step_key: null, state_payload: { agentic_canvas: scene }, active_scene_seed: scene, active_scene_contract: { scene_id: `visual-${pattern.toLowerCase()}`, scene_version: 1, subject_key: "CANVAS", subject_profile_version: "agentic-canvas-profile-v2", activity_key: "agentic_canvas", activity_contract_version: "agentic-canvas-activity-v1", renderer_key: "agentic-canvas", renderer_version: "agentic-canvas-renderer-v2", payload_schema_version: "agentic-canvas-scene-v2", locale: value.direction === "rtl" ? "ar" : "en", direction: value.direction } };
}

function App() { const [pattern, setPattern] = useState<Pattern>("NUMBER_LINE"); const current = snapshot(pattern); return <main className="visual-proof" dir={definitions[pattern].direction} data-pattern={pattern}><header><p>Authenticated-independent production renderer proof</p><h1>Canvas visual intelligence</h1></header><nav>{(Object.keys(definitions) as Pattern[]).map(key => <button key={key} aria-pressed={pattern === key} onClick={() => setPattern(key)}>{key}</button>)}</nav><p data-objective>{definitions[pattern].objective}</p><div className="daily-shell"><StudioRendererHost snapshot={current} operationPending={false} onOperation={async () => {}} onReload={() => {}}/></div></main>; }
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
