import React, { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";

import { StudioRendererHost } from "../../components/daily-student/studio-renderer-host";
import type { StudioSnapshotFrame } from "../../lib/studio/contracts";

type Pattern = "NUMBER_LINE" | "PLOT" | "CYCLE" | "SHAPES" | "ARABIC" | "OLDER" | "CUSTOM" | "FULL_POWER";

const base = { meaning: "Use the visual relationship to explain the idea.", accessibility: { text_equivalent: "A tutor-approved educational visual.", aria_label: "Educational visual" }, allowed_actions: ["FOCUS"], elements: [{ id: "focus", label: "Focus point", current_value: null }] } as const;
const math = (kind: "NUMBER_LINE" | "PLOT") => ({ ...base, block_id: `${kind.toLowerCase()}-board`, type: "MATH_BOARD" as const, title: kind === "PLOT" ? "Plot positions on a coordinate grid" : "Compare fractions on a number line", board_kind: kind, axis_min: "-4", axis_max: "4", axes: kind === "PLOT" ? [{ axis: "X" as const, minimum: "-4", maximum: "4", step: "1" }, { axis: "Y" as const, minimum: "-3", maximum: "3", step: "1" }] : [{ axis: "X" as const, minimum: "0", maximum: "1", step: "1/4" }], markers: kind === "PLOT" ? [{ id: "origin", label: "0", value: "0", marker_kind: "POINT" as const, draggable: false }, { id: "three", label: "3", value: "3", marker_kind: "POINT" as const, draggable: false }] : [{ id: "half", label: "1/2", value: "1/2", marker_kind: "POINT" as const, draggable: false }, { id: "three-quarters", label: "3/4", value: "3/4", marker_kind: "POINT" as const, draggable: false }], expressions: [] });
const definitions: Record<Pattern, { objective: string; direction: "ltr" | "rtl"; blocks: any[]; presentation: any }> = {
  NUMBER_LINE: { objective: "Place equivalent fractions precisely.", direction: "ltr", blocks: [math("NUMBER_LINE")], presentation: { layout: "FOCUS", palette: "COOL", motion: "NONE", placements: [{ block_id: "number_line-board", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: [] } },
  PLOT: { objective: "Read positions through x and y axes.", direction: "ltr", blocks: [math("PLOT")], presentation: { layout: "SPLIT", palette: "COOL", motion: "SUBTLE", placements: [{ block_id: "plot-board", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: [] } },
  CYCLE: { objective: "Trace a changing system around a cycle.", direction: "ltr", blocks: [{ ...base, block_id: "cycle", type: "DIAGRAM", title: "Water changes and returns", topology: "CYCLE", layout: "RADIAL", nodes: ["Evaporate", "Condense", "Collect", "Warm"].map((label, index) => ({ id: `cycle-${index}`, label, node_kind: "PROCESS" as const })), edges: [0, 1, 2, 3].map(index => ({ source_id: `cycle-${index}`, target_id: `cycle-${(index + 1) % 4}`, relation: index === 3 ? "RETURNS_TO" as const : "NEXT" as const, label: null })) }], presentation: { layout: "FOCUS", palette: "NATURE", motion: "REVEAL", placements: [{ block_id: "cycle", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: ["cycle"] } },
  SHAPES: { objective: "Name the shape and directional relationship.", direction: "ltr", blocks: [{ ...base, block_id: "shapes", type: "SCENE_2D", title: "Geometry field", viewport_width_units: 100, viewport_height_units: 100, objects: [{ id: "point", label: "Point", object_kind: "POINT", position: { x: "15", y: "30" }, draggable: false }, { id: "polygon", label: "Polygon", object_kind: "POLYGON", position: { x: "45", y: "55" }, draggable: false }, { id: "arrow", label: "moves", object_kind: "ARROW", position: { x: "68", y: "55" }, draggable: false }, { id: "label", label: "Target", object_kind: "LABEL", position: { x: "88", y: "55" }, draggable: false }], relations: [{ source_id: "arrow", target_id: "label", relation: "MOVES_TOWARD", label: "toward" }] }], presentation: { layout: "GRID", palette: "VIBRANT", motion: "NONE", placements: [{ block_id: "shapes", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: [] } },
  ARABIC: { objective: "رتّب المراحل ثم اشرح كيف يعود الماء إلى البداية.", direction: "rtl", blocks: [{ ...base, block_id: "arabic-cycle", type: "DIAGRAM", title: "دورة الماء", topology: "CYCLE", layout: "RADIAL", nodes: ["تبخر", "تكاثف", "هطول", "تجميع"].map((label, index) => ({ id: `ar-${index}`, label, node_kind: "PROCESS" as const })), edges: [0, 1, 2, 3].map(index => ({ source_id: `ar-${index}`, target_id: `ar-${(index + 1) % 4}`, relation: index === 3 ? "RETURNS_TO" as const : "NEXT" as const, label: null })) }], presentation: { layout: "FOCUS_SUPPORT", palette: "NATURE", motion: "REVEAL", placements: [{ block_id: "arabic-cycle", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: ["arabic-cycle"] } },
  OLDER: { objective: "Compare the same fractions with denser supporting evidence.", direction: "ltr", blocks: [math("NUMBER_LINE"), { ...base, block_id: "support", type: "TEXT_INTERACTION", title: "Compare", interaction_family: "RELATION", prompt: "Connect each claim to the number line.", groups: [{ id: "evidence", label: "Evidence" }], items: [{ id: "claim", text: "3/4 lies to the right of 1/2.", group_id: "evidence" }], relations: [] }], presentation: { layout: "GRID", palette: "NEUTRAL", motion: "NONE", placements: [{ block_id: "number_line-board", role: "PRIMARY", order: 0, span: "WIDE" }, { block_id: "support", role: "SUPPORT", order: 1, span: "NORMAL" }], reveal_order: [] } },
  CUSTOM: { objective: "Compare two exact fractions by moving a shared focal marker.", direction: "ltr", blocks: [{ ...base, block_id: "fraction-sandbox", type: "CUSTOM_VISUAL", title: "Interactive fraction lens", allowed_actions: ["MOVE"], elements: [{ id: "fraction-a", label: "one half", current_value: "1/2" }], artifact_instance_id: "fraction-sandbox-instance", bridge_nonce: "sandbox-proof-123", parameters: { label: "1/2" }, package: { version: "custom-visual-package-v1", runtime_kind: "custom-visual", dependencies: ["native-svg-v1"], parameter_schema: { type: "object", properties: { label: { type: "string" } } }, manifest: { version: "canvas-semantic-manifest-v1", brief_digest: "a".repeat(64), objective: "Compare fractions.", representation_summary: "A movable focal fraction marker on a shared fraction lens.", entities: [{ semantic_id: "fraction-a", kind: "quantity", label: "one half", educational_meaning: "An exact fraction.", visible_description: "A movable blue marker." }], relations: [], quantities: [{ semantic_id: "fraction-a", value: "1/2", unit: null, provenance: "tutor-brief" }], presentation_steps: [], interactions: [{ semantic_id: "fraction-a", action: "MOVE", meaning: "Move the focal marker.", value_required: true }], calculated_results: [], visual_descriptions: ["A connected fraction lens."], current_state_schema: { active_focus: "semantic-id" }, provenance: { runtime_kind: "custom-visual", brief_digest: "a".repeat(64) } }, source: "window.mount=(root,params,bridge)=>{root.innerHTML='<svg viewBox=\"0 0 680 220\" role=\"img\" aria-label=\"fraction lens\"><path d=\"M70 126 H610\" stroke=\"#173f5f\" stroke-width=\"8\" stroke-linecap=\"round\"/><path d=\"M70 126 H340\" stroke=\"#57b8ff\" stroke-width=\"20\" stroke-linecap=\"round\"/><circle cx=\"340\" cy=\"126\" r=\"25\" fill=\"#1769aa\"/><text x=\"340\" y=\"72\" text-anchor=\"middle\" fill=\"#0f2c44\" font-size=\"30\">'+params.label+'</text></svg><button type=\"button\">Move marker</button>';root.querySelector('button').onclick=()=>bridge.emit('MOVE','fraction-a',{from_value:params.label,to_value:'3/4'});}" } }], presentation: { layout: "FOCUS", palette: "COOL", motion: "SUBTLE", placements: [{ block_id: "fraction-sandbox", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: [] } },
  FULL_POWER: { objective: "Compare continuously coupled slopes by dragging points A and B.", direction: "ltr", blocks: [{ ...base, block_id: "slope_compare_activity", type: "CUSTOM_VISUAL", title: "Compare slopes by dragging A and B", meaning: "A connected coordinate-plane activity with exact live rise, run, and slope.", allowed_actions: ["MOVE", "SELECT"], elements: [{ id: "point_a", label: "Point A", current_value: null }, { id: "point_b", label: "Point B", current_value: null }, { id: "choice_a", label: "A is steeper", current_value: null }, { id: "choice_b", label: "B is steeper", current_value: null }], artifact_instance_id: "slope_compare_activity-artifact", bridge_nonce: "e5484b4771d9ed4dd223e6a633fa71f4", custom_visual_build_id: "555f790a-c452-49df-b009-b0178a403783", manifest_digest: "6072feb5187296c682c4f03e7bc01622d39917610534402e6ca3728ebf04caf6", parameters: { a_x: 2, a_y: 1, b_x: 3, b_y: 4, x_max: 8, y_max: 8 } }], presentation: { layout: "FOCUS", palette: "COOL", motion: "SUBTLE", placements: [{ block_id: "slope_compare_activity", role: "PRIMARY", order: 0, span: "FULL" }], reveal_order: [] } },
};

function snapshot(pattern: Pattern): StudioSnapshotFrame {
  const value = definitions[pattern]; const fullPower = pattern === "FULL_POWER"; const scene = { version: fullPower ? "agentic-canvas-scene-v3" : "agentic-canvas-scene-v2", objective: value.objective, subject_key: "MATH", presentation: value.presentation, blocks: value.blocks };
  return { protocol_version: "studio-protocol-v1", type: "STUDIO_SNAPSHOT", latest_event_sequence: 0, snapshot_schema_version: "studio-snapshot-v1", current_scene_id: `visual-${pattern.toLowerCase()}`, current_scene_version: 1, active_subject_key: "CANVAS", active_activity_key: "agentic_canvas", active_step_key: null, state_payload: { agentic_canvas: scene }, active_scene_seed: scene, active_scene_contract: { scene_id: `visual-${pattern.toLowerCase()}`, scene_version: 1, subject_key: "CANVAS", subject_profile_version: fullPower ? "agentic-canvas-profile-v3" : "agentic-canvas-profile-v2", activity_key: "agentic_canvas", activity_contract_version: "agentic-canvas-activity-v1", renderer_key: "agentic-canvas", renderer_version: fullPower ? "agentic-canvas-renderer-v3" : "agentic-canvas-renderer-v2", payload_schema_version: fullPower ? "agentic-canvas-scene-v3" : "agentic-canvas-scene-v2", locale: value.direction === "rtl" ? "ar" : "en", direction: value.direction } };
}

function App() { const [pattern, setPattern] = useState<Pattern>("NUMBER_LINE"); const [operation, setOperation] = useState(""); const current = snapshot(pattern); return <main className="visual-proof" dir={definitions[pattern].direction} data-pattern={pattern}><header><p>Authenticated-independent production renderer proof</p><h1>Canvas visual intelligence</h1></header><nav>{(Object.keys(definitions) as Pattern[]).map(key => <button key={key} aria-pressed={pattern === key} onClick={() => setPattern(key)}>{key}</button>)}</nav><p data-objective>{definitions[pattern].objective}</p><p data-last-operation>{operation}</p><div className="daily-shell"><StudioRendererHost snapshot={current} operationPending={false} onOperation={async value => setOperation(`${value.action_key}:${String(value.payload.element_id)}:${String(value.payload.to_value)}`)} onReload={() => {}}/></div></main>; }
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
