"""track learning session activity

Revision ID: 4f3f83db9c50
Revises: da9f02c7cbeb
Create Date: 2026-08-20 14:08:39.436810
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f3f83db9c50'
down_revision: Union[str, None] = 'da9f02c7cbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'last_activity_at')
    # ### end Alembic commands ###