"""content vector index

Revision ID: 7ff4a50f3429
Revises: a066e6626ee8
Create Date: 2026-08-20 13:58:55.837207
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


revision: str = '7ff4a50f3429'
down_revision: Union[str, None] = 'a066e6626ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_blocks', sa.Column('embedding', Vector(dim=8), nullable=True))
    op.create_index('ix_content_blocks_embedding', 'content_blocks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_l2_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_blocks_embedding', table_name='content_blocks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_l2_ops'})
    op.drop_column('content_blocks', 'embedding')
    # ### end Alembic commands ###
