"""learning intelligence foundation

Revision ID: a066e6626ee8
Revises: 0007_content_structural_runs
Create Date: 2026-08-20 13:57:59.837239
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a066e6626ee8'
down_revision: Union[str, None] = '0007_content_structural_runs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_processing_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('rubric_version', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='COMPLETED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=32), server_default='MATH', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='OPEN', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_sessions_student_status', 'learning_sessions', ['student_id', 'status'], unique=False)
    op.create_table('current_learning_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('state_type', sa.String(length=64), nullable=False),
    sa.Column('concept_ref', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['intelligence_processing_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_current_learning_states_student_status', 'current_learning_states', ['student_id', 'status'], unique=False)
    op.create_table('decision_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('concept_ref', sa.String(length=128), nullable=False),
    sa.Column('mastery', sa.String(length=32), nullable=False),
    sa.Column('evidence_confidence', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['intelligence_processing_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'processing_run_id', 'concept_ref', name='uq_decision_view_run_concept')
    )
    op.create_table('learner_intelligence_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['intelligence_processing_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'processing_run_id', name='uq_intelligence_card_run')
    )
    op.create_table('learner_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('pattern_type', sa.String(length=64), nullable=False),
    sa.Column('pattern_key', sa.String(length=128), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='CANDIDATE', nullable=False),
    sa.Column('support_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('counter_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['intelligence_processing_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'pattern_type', 'pattern_key', 'scope', name='uq_learner_pattern_scope')
    )
    op.create_index('ix_learner_patterns_student_status', 'learner_patterns', ['student_id', 'status'], unique=False)
    op.create_table('learning_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_messages_session_created', 'learning_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('candidate_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('concept_ref', sa.String(length=128), nullable=True),
    sa.Column('signal', sa.String(length=128), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['learning_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_events_session', 'candidate_events', ['session_id'], unique=False)
    op.create_table('learning_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('candidate_event_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('concept_ref', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_event_id'], ['candidate_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['intelligence_processing_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['learning_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_events_run_session', 'learning_events', ['processing_run_id', 'session_id'], unique=False)
    op.create_table('learning_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('concept_ref', sa.String(length=128), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relationship', sa.String(length=32), server_default='insufficient', nullable=False),
    sa.Column('source_ref', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['learning_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_evidence_event', 'learning_evidence', ['event_id'], unique=False)
    op.create_table('pattern_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['learning_evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['learner_patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_id', 'evidence_id', name='uq_pattern_evidence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pattern_evidence')
    op.drop_index('ix_learning_evidence_event', table_name='learning_evidence')
    op.drop_table('learning_evidence')
    op.drop_index('ix_learning_events_run_session', table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index('ix_candidate_events_session', table_name='candidate_events')
    op.drop_table('candidate_events')
    op.drop_index('ix_learning_messages_session_created', table_name='learning_messages')
    op.drop_table('learning_messages')
    op.drop_index('ix_learner_patterns_student_status', table_name='learner_patterns')
    op.drop_table('learner_patterns')
    op.drop_table('learner_intelligence_cards')
    op.drop_table('decision_views')
    op.drop_index('ix_current_learning_states_student_status', table_name='current_learning_states')
    op.drop_table('current_learning_states')
    op.drop_index('ix_learning_sessions_student_status', table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_table('intelligence_processing_runs')
    # ### end Alembic commands ###