"""version pattern derivations

Revision ID: da9f02c7cbeb
Revises: 7ff4a50f3429
Create Date: 2026-08-20 14:02:20.804912
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'da9f02c7cbeb'
down_revision: Union[str, None] = '7ff4a50f3429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_learner_pattern_scope', 'learner_patterns', type_='unique')
    op.create_unique_constraint('uq_learner_pattern_scope', 'learner_patterns', ['student_id', 'processing_run_id', 'pattern_type', 'pattern_key', 'scope'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_learner_pattern_scope', 'learner_patterns', type_='unique')
    op.create_unique_constraint('uq_learner_pattern_scope', 'learner_patterns', ['student_id', 'pattern_type', 'pattern_key', 'scope'])
    # ### end Alembic commands ###